spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: false

  mail:
    host: ${MAILTRAP_HOST:localhost}
    port: ${MAILTRAP_PORT:1025}
    username: ${MAILTRAP_USERNAME:}
    password: ${MAILTRAP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false