export enum ErrorCode {
    // General Errors
    INTERNAL_ERROR = 'INTERNAL_ERROR',

    // Shopping List Errors
    // SHOPPING_LIST_NOT_FOUND = 'SHOPPING_LIST_NOT_FOUND',
    // SHOPPING_LIST_TITLE_REQUIRED = 'SHOPPING_LIST_TITLE_REQUIRED',
    // ITEM_QUANTITY_INVALID = 'ITEM_QUANTITY_INVALID',
}
